spring:
  datasource:
#    url: jdbc:mysql://mydbinstance1.ctgutwvlrngx.rds.cn-north-1.amazonaws.com.cn:3306/zhiyuan?characterEncoding=utf-8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
#    username: root
#    password: bmw888bmw
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://180.76.52.59:3306/zhiyuan?serverTimezone=GMT%2B8
    username: zhiyuan
    password: QQ@1607247596
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html

server:
  port: 9900
  servlet:
    session:
      cookie:
        max-age: 604800
mybatis:
  type-aliases-package: com.sanelee.zhiyuan.Model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
jdbc:
  connectionURL: jdbc:mysql://localhost:3306/zhiyuan?serverTimezone=GMT%2B8
  driverClass: com.mysql.cj.jdbc.Driver
#  connectionURL: jdbc:mysql://mydbinstance1.ctgutwvlrngx.rds.cn-north-1.amazonaws.com.cn:3306/zhiyuan?characterEncoding=utf-8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
logging:
  level:
    com.sanelee.zhiyuan.Mapper: DEBUG
